import streamlit as st
import pandas as pd
import numpy as np
import joblib

st.set_page_config(page_title="Heart Disease Risk Predictor", page_icon="❤️", layout="centered")

# ---------- Load model ----------
@st.cache_resource
def load_model():
    return joblib.load("framingham_final_lr_model.joblib")

bundle = load_model()
preprocessor = bundle["preprocessor"]
model = bundle["model"]
num_cols = bundle["num_cols"]
cat_cols = bundle["cat_cols"]

st.title("❤️ Heart Disease Risk Prediction")
st.caption(
    "A machine learning-based clinical decision-support tool using Logistic Regression, "
    "trained on the Framingham Heart Study dataset. This tool is intended to support, "
    "not replace, clinical judgment."
)

st.markdown("---")
st.subheader("Patient Information")

col1, col2 = st.columns(2)

with col1:
    age = st.number_input("Age (years)", min_value=20, max_value=100, value=50)
    gender = st.selectbox("Gender", ["Male", "Female"])
    education = st.selectbox(
        "Education Level",
        ["uneducated", "primaryschool", "graduate", "postgraduate"],
    )
    current_smoker = st.selectbox("Current Smoker?", ["No", "Yes"])
    cigs_per_day = st.number_input(
        "Cigarettes per Day", min_value=0, max_value=70, value=0,
        help="0 if non-smoker. Smoking intensity matters more than smoker status alone.",
    )
    bp_meds = st.selectbox("On Blood Pressure Medication?", ["No", "Yes"])
    prevalent_stroke = st.selectbox("History of Stroke?", ["No", "Yes"])
    prevalent_hyp = st.selectbox("Hypertension?", ["No", "Yes"])

with col2:
    diabetes = st.selectbox("Diabetes?", ["No", "Yes"])
    tot_chol = st.number_input("Total Cholesterol (mg/dL)", min_value=100, max_value=700, value=200)
    sys_bp = st.number_input("Systolic Blood Pressure (mmHg)", min_value=80, max_value=300, value=120)
    dia_bp = st.number_input("Diastolic Blood Pressure (mmHg)", min_value=40, max_value=150, value=80)
    bmi = st.number_input("BMI", min_value=10.0, max_value=60.0, value=25.0, step=0.1)
    heart_rate = st.number_input("Resting Heart Rate (bpm)", min_value=40, max_value=150, value=75)
    glucose = st.number_input("Glucose (mg/dL)", min_value=30, max_value=400, value=80)

st.markdown("---")

if st.button("Predict Heart Disease Risk", type="primary", use_container_width=True):
    input_dict = {
        "age": age,
        "Gender": gender,
        "education": education,
        "currentSmoker": 1 if current_smoker == "Yes" else 0,
        "cigsPerDay": cigs_per_day,
        "BPMeds": 1 if bp_meds == "Yes" else 0,
        "prevalentStroke": "yes" if prevalent_stroke == "Yes" else "no",
        "prevalentHyp": 1 if prevalent_hyp == "Yes" else 0,
        "diabetes": 1 if diabetes == "Yes" else 0,
        "totChol": tot_chol,
        "sysBP": sys_bp,
        "diaBP": dia_bp,
        "BMI": bmi,
        "heartRate": heart_rate,
        "glucose": glucose,
    }
    input_df = pd.DataFrame([input_dict])

    X_proc = preprocessor.transform(input_df)
    proba = model.predict_proba(X_proc)[0][1]
    pred = model.predict(X_proc)[0]

    st.markdown("### Result")
    risk_pct = proba * 100

    if pred == 1:
        st.error(f"**Elevated Risk Indicated** — Estimated probability of heart disease: **{risk_pct:.1f}%**")
    else:
        st.success(f"**Lower Risk Indicated** — Estimated probability of heart disease: **{risk_pct:.1f}%**")

    st.progress(min(int(risk_pct), 100))

    st.info(
        "⚠️ This prediction is generated by a statistical model trained on a limited dataset and is "
        "**not a medical diagnosis**. Please consult a qualified healthcare professional for clinical evaluation. "
        "Note: this model uses a class-balanced threshold to prioritize catching at-risk patients (higher recall), "
        "which means it may flag more false positives than a standard model — appropriate for a screening tool, "
        "not a diagnostic one."
    )

    with st.expander("See input summary"):
        st.dataframe(input_df, use_container_width=True)

st.markdown("---")
st.caption(
    "Model: Logistic Regression (class-balanced) | Trained on the Framingham Heart Study dataset "
    "(4,238 records) | 10-fold CV ROC-AUC ≈ 0.72, PR-AUC ≈ 0.35, Recall ≈ 0.67"
)
